version: '3'

services:
    db:
        image: mysql:8.0
        container_name: mysql_host
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DATABASE}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_USER_PASSWORD}
            TZ: '${TZ}'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./docker/db/data:/var/lib/mysql
            - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./docker/db/sql:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
        networks: 
            - mynet
    app:
        environment:
            DATABASE: ${DATABASE}
            DB_USER: ${DB_USER}
            DB_USER_PASSWORD: ${DB_USER_PASSWORD}
        build: 
            context: ./app
        ports: 
            - "8080:8080"
        depends_on: 
            - db
        networks: 
            - mynet

networks: 
    mynet:
        driver: bridge